config/routes.rb
  

  

Story::Application.routes.draw do

  

  resources :plotphotos

  resources :talephotos

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"} 
  get '/users', to: 'users#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
   resources :users , only: [:edit, :update]

   resource :user, only: [:edit] do
     collection do
       patch 'update_role'
     end
   end
   resources :tales

  root  'tales#index'# =>, filter: "Story"
  get 'tales/list', to: 'tales#tales_list'
  get "homepages/index"
  get "activities/index"
  get "journals/index"
  resources :contacts
  resources :bios
  resources :invitations
  resources :sharings
  resources :follows
  get "profiles/index"

  
  
  
  get "/pages/id", to: 'pages#show'
  resources :fruits
  
  resources :plots do
    member do
      post 'update'
    end
  end
  

  match 'featured_stories', :controller => 'tales', :action => 'featured_stories', :via => [:get]
  match 'trending_stories', :controller => 'tales', :action => 'trending_stories', :via => [:get]
  match 'tales/new',  :controller => 'tales', :action => 'new', :via => [:post]
  match 'tales/:id',  :controller => 'tales', :action => 'show', :via => [:get]
  match 'profiles/:id', :controller => 'profiles', :action => 'index', :via => [:get]
  match 'profilesOf', :controller => 'profiles', :action => 'follow', :via => [:get, :post,:delete]
  match 'profilesOfU', :controller => 'profiles', :action => 'unfollow', :via => [:get, :post,:delete]

  match 'talesOf', :controller =>  'tales', :action => 'follow', :via => [:get, :post,:delete]
  match 'talesOfU', :controller => 'tales', :action => 'unfollow', :via => [:get, :post,:delete]

  match 'likesOf', :controller => 'tales', :action => 'like', :via => [:get, :post,:delete]
  match 'likesOfU', :controller => 'tales', :action => 'unlike', :via => [:get, :post,:delete]

  
  match 'fruit',:controller => 'fruits', :action => 'ruin', :via => [:get, :post,:delete]

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!, only: [ :follow, :unfollow]

  def index
    @userFirstName = User.where(id: params[:format]).pluck(:firstname)
    @followers = Follow.where(followable_type: User, followable_id: params[:format]).pluck(:follower_id)
    @followings = Follow.where(follower_type: User, follower_id: params[:format],followable_type: User).pluck(:followable_id)
    @numberOfFollowers = Follow.where(followable_type: User, followable_id: params[:format]).count
    @numberOfFollowings = Follow.where(follower_type: User, follower_id: params[:format],followable_type: User).count
    @idOfStoriesFollowedByMe = Follow.where(follower_type: User, follower_id: params[:format],followable_type: Tale).pluck(:followable_id)
    @numberOfFollowingsTale = Follow.where(follower_type: User, follower_id: params[:format],followable_type: Tale).count
    @bio = Bio.where(user_id: params[:format])
    
    @story_by_me = Tale.where(user_id: params[:format]).order(:updated_at).reverse
    @published_story_by_me = Tale.where(user_id: params[:format], private_flag: 0).order(:updated_at).reverse
    @number_of_stories_created_by_me = Tale.where(user_id: params[:format]).count
    
    @storiesFollowedByMe = Tale.where(id: @idOfStoriesFollowedByMe)



  end

  def follow

     #follow author 
  	 current_user.follow!(User.find(params[:followings_id]))
     


     redirect_to profiles_index_path(User.find(params[:followings_id])) 


     #create notification
     n = Journal.new
     n.notification_type = "Follow"
     identities = Follow.where(follower_id: current_user.id, followable_type: User, followable_id: params[:followings_id]).pluck(:id)
     n.notification_id = identities[0]
     n.notification_to = params[:followings_id]
     n.save

     social_identity = Identity.where(user_id: params[:followings_id], provider: "facebook")
     
     
     if(social_identity[0]!=nil)

              notification_string = current_user.firstname + " starts following you"
              @g = Koala::Facebook::API.new(Koala::Facebook::OAuth.new("878916972138133","1c19d3ff9cf496854d4e506030f592b1").get_app_access_token)
              @g.put_connections(social_identity[0].uid, "notifications", template: notification_string, href: "http://ryte.club")



     end         



     				
  end

  def unfollow
  	 
     #remove notification 
     identities = Follow.where(follower_id: current_user.id, followable_type: User, followable_id: params[:followings_id]).pluck(:id)
     journal = Journal.where(notification_type: "Follow", notification_id: identities[0], notification_to: params[:followings_id])
     Journal.delete(journal)

     #unfollow author
     current_user.unfollow!(User.find(params[:followings_id]))


     redirect_to profiles_index_path(User.find(params[:followings_id]))				 				
 		  	
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_bio.html.erb
  <% if user_signed_in? and current_user.id.to_s==params[:format].to_s %>
      <div class = "profile-edit-button">
      <span class="octicon octicon-pencil" data-toggle="tooltip" data-placement="top" data-original-title="Edit your bio"></span>

      </div>  
      <div class = "profile-bio-info">
      </div>
      <div class= "profile-bio-new" contenteditable="true">
      </div>

      
      <script>
      $(document).ready(function(){
      

       // disable inline editing of ckeditor.
       CKEDITOR.disableAutoInline = true;


        var commandValue = 0;
        //tooltip initilized
        $('[data-toggle="tooltip"]').tooltip();  

        

        $('.profile-bio-new').css('border','none'); 
        $('.profile-edit-button').hide();
        //Check whether the bio is null
        //arrage DOM according to that 
         $.ajax({
                  type: "GET",
                  url: "/bios/",
                  contentType: "application/json; charset=utf-8",
                  dataType: "json",
                  data: "",
                  success: function(data){
                          var tale_index;
                          for(var i = 0;data[i];i++){
                            if(data[i].user_id=="<%= current_user.id %>"){
                              $('.profile-bio-info').hide();
                              $('.profile-bio-new').show();
                              $('.profile-bio-new').html(data[i].title);
                              $('.profile-edit-button').show();
                               var texts = $('.profile-bio-new').text();
                    if(!texts.trim()){
                        $('.profile-bio-new').hide();
                        $('.profile-bio-info').html("Add your short bio");
                        $('.profile-bio-info').show();
                        $('.profile-edit-button').hide();                  
                        }
                    else{
                        $('.profile-edit-button').show();
                        }

                              commandValue = 1; //command value 1 indicates PUT operation
                              break;
                            }
                            else{
                              
                              $('.profile-bio-info').html("Add your short bio");
                              $('.profile-bio-info').show();
                              $('.profile-bio-new').hide();
                              $('.profile-edit-button').hide();
                            }
                          }

                          if(data.length==0){
                            $('.profile-bio-info').html("Add your short bio");
                              $('.profile-bio-info').show();
                              $('.profile-bio-new').hide();
                              $('.profile-edit-button').hide();
                          }  

                        }});
                 


        
        
$('.profile-bio-info').mouseup(function(){
                $(this).html("");
                $('.profile-bio-new').show();
                $('.profile-bio-new').focus();
                $('.profile-bio-new').css('border',' 1px solid gray');              
                });
        



        function autoSaveBio(context,command){
          var id_of_content;
            if(command ==0){
                          var  talemeta =  { 
                                            "user_id": "<%= current_user.id %>",
                                            "title": "" 
                                            };         
                      
                          talemeta.title =  safe_tags($(context).html());
                          //post operation 
                          $.ajax({
                                    type: "POST",
                                    url: "/bios" ,
                                    contentType: "application/json; charset=utf-8",
                                    dataType: "json",
                                    data: JSON.stringify(talemeta),
                                    success: function(){ }
                                  });
                          commandValue = 1;
                         
                                                      
                        }
         

         if(command == 1){ //put operation 
                  //get the info for updating tale id
                  $.ajax({
                  type: "GET",
                  url: "/bios/",
                  contentType: "application/json; charset=utf-8",
                  dataType: "json",
                  data: "",
                  success: function(data){
                          var tale_index;
                          for(var i = 0;data[i];i++){
                            if(data[i].user_id=="<%= current_user.id %>"){
                              tale_index = data[i].id;
                              break;  
                            }
                          }
                          
                          
                          
                          var  talemeta =  { "id": tale_index ,
                                            "user_id": "<%= current_user.id %>",
                                            "title": "" 
                                            };  
                          talemeta.title =  safe_tags($(context).html());
                          $.ajax({
                                  type: "PUT",
                                  url: "/bios/"+ talemeta.id ,
                                  contentType: "application/json; charset=utf-8",
                                  dataType: "json",
                                  data: JSON.stringify(talemeta),
                                  success: function(){
                                        }
                                  });


                          
                                      }

                              });
                            }          

    }
  




        function safe_tags(str) {
          
            return str.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g," ").replace(/<br>/g,"").replace(/<div>/g,"").replace(/<\/div>/g,"") ;
        }



        $('.profile-edit-button').mouseup(function(){
                $('.profile-bio-new').focus();                
        });

        $('.profile-bio-new').focus(function(){
          $('.profile-edit-button').hide();
        });


      
        var contents =  $('.profile-bio-new');

        $('.profile-bio-new').on('keyup',function(e){      
              if(e.keyCode==13 && !e.shiftKey)
              {
                  // prevent default behavior
                  e.preventDefault();
                  $(this).blur();    
              }  
        });

        
        $('.profile-bio-new').on('blur',function(e){
                  $(this).css('border','none');  
                  //extracting the text from Html
                  var texts = $('.profile-bio-new').text();

                  if (contents!=$(this)){
                    autoSaveBio(e.target, commandValue);
                    }                   



                    if(!texts.trim()){
                        $('.profile-bio-new').hide();
                        $('.profile-bio-info').html("Add your short bio");
                        $('.profile-bio-info').show();
                        $('.profile-edit-button').hide();                  
                        }
                    else{
                        $('.profile-edit-button').show();
                        }
        });
      });
      </script>

  
<% else %>
                 <% if @bio[0]!= nil %>
              <div class="profile-bio-new">
                  <%= @bio[0].title.html_safe %>
                  </div>
                  <script>
            
            $(document).ready(function(){  
                    $('.profile-bio-new').html(safe_tags($(this));
                  });

          function safe_tags(str){  
            return str.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g," ").replace(/<br>/g,"").replace(/<div>/g,"").replace(/<\/div>/g,"");}
            </script>

                 <% end %> 
<% end %>






<style>
.octicon-pencil{
  font-size: 1vw;
}
</style>

app/views/profiles/_contribution.html.erb
<strong>Contributed by <%= @userFirstName[0] %></strong> <br />
<div>
<% plots =  Plot.where(user_id: params[:format]).order(:created_at) %>
<% if plots ==[]  %> 
<%= @userFirstName[0] %> didn't contributed to any story <br />
<% else %>

<% plots.each do |p| %>
	<%= link_to  @userFirstName[0], profiles_index_path(params[:format]) %> contributed in 
		<% titles = Tale.where(id: p.tale_id).pluck('title') %>
		
	<% url = url_for(:controller => 'plots', :action => 'new', :tale_id => p.tale_id)  %>
	<%= link_to titles[0],url %><br />

<% end %>


<br />
<% end %>
</div>

app/views/profiles/_follow.html.erb
<% if user_signed_in? %>
<div>

<% if params[:format].to_s!=current_user.id.to_s %>
	<% if current_user.follows?(User.find(params[:format])) %>
		<% url1 = url_for(:controller => 'profiles', :action => 'unfollow', :followings_id => params[:format] )  %>
		<strong><%= link_to "unfollow",url1, class: "button" %></strong>
	<% else %>
		<% url = url_for(:controller => 'profiles', :action => 'follow', :followings_id => params[:format] )  %>
		<strong><%= link_to "follow",url, class: "button" %></strong>
	<% end %>
<% end %>






</div>	
<% end %>

<div class="follow-container">
	<div class = "follower-box">

		<% if @numberOfFollowers>1 %>
		<%=link_to @numberOfFollowers.to_s+" Followers", profiles_index_path(params[:format], filter: "followers") %> 
		<% else %>
		<%=link_to @numberOfFollowers.to_s+" Follower", profiles_index_path(params[:format], filter: "followers") %> 
		<% end %>&nbsp;&nbsp;&nbsp;
		|&nbsp;&nbsp;&nbsp;

		<% if @numberOfFollowings>1 %>
		<%=link_to @numberOfFollowings.to_s+" Followings", profiles_index_path(params[:format], filter: "followings") %> 
		
		<% else %>
		<%=link_to @numberOfFollowings.to_s+" Following", profiles_index_path(params[:format], filter: "followings") %> 
		<% end %> 
	<div class= "bio">
<% if @bio[0] == nil %>
	<% if user_signed_in? and current_user.id.to_s==params[:format].to_s %>
			<%= link_to "Add Your Short Bio",bios_path %>
	<% end %>	
<% else %>
	<% if user_signed_in? and current_user.id.to_s==params[:format].to_s %>
	<%= link_to @bio[0].bio, edit_bio_path(@bio[0].id) %>
	<% else %>
	<%= @bio[0].bio %>
	<% end %>
<% end %>
</div>

	</div>





</div>

app/views/profiles/_follow_track.html.erb
  <div class="follow-track"> 
      <% if @numberOfFollowings<2 %>  
        <p class="follow-user"> Follows  <%= @numberOfFollowings %> user </p>
      <% else %>
        <p class="follow-user"> Follows  <%= @numberOfFollowings %> users </p>
      <% end %>

      <% if @numberOfFollowers<2 %> 
        <p class="followed-by"> Followed by <%= @numberOfFollowers %> user </p>
      <% else %>
        <p class="followed-by"> Followed by <%= @numberOfFollowers %> users </p>
      <% end %>

      <%# if @numberOfFollowingsTale<2 %>  
      <!--  <p class="follow-stories"> Follows <%= @numberOfFollowingsTale %> stories </p> -->
      <%# else %>
        <!-- <p class="follow-stories"> Follows <%= @numberOfFollowingsTale %> stories </p> -->
      <%# end %>
   </div><!-- end of follow-track -->
   

app/views/profiles/_followers.html.erb
<%= render "top" %>
<script>
/*	$(document).ready(function(){
	$('.f-button').each(function(){
	var counter = 0;
	$(this).mouseover(function(){
		if(counter%2==0)
		$(this).html("<a class='octicon octicon-check'></a>");
		else
		$(this).html("<a class='octicon octicon-x'></a>");	
		});

	$(this).mouseleave(function(){
		if(counter%2==0)
		$(this).html("<a class='octicon octicon-plus'></a>");
		else
		$(this).html("<a class='octicon octicon-check'></a>");	
		});


	$(this).mouseup(function(){	
	counter++;
		if(counter%2==0) $(this).html("<a class='octicon octicon-plus'></a>");
 		else 
 		$(this).html("<a class='octicon octicon-check'></a>");
 		$(this).toggleClass('f-button-clicked',counter%2!=0);
		});
	});	
 });
*/

</script>




<% if @numberOfFollowers>0 %>

<div class="follower-container">
<% if @numberOfFollowers>1 %>
<h4>Followers</h4>
<% else %>
<h4>Follower</h4>
<% end %>

</div>	





<div class="follower-container">	
<div class="col-4 col-sm-4 col-lg-4">
     		<% count = 1 %>
	  		<% @followers.each do |follower| %>
			<% if count%3==0 %>



      		<div class ="thumbnail">
      		<% social_identity = Identity.where(user_id: follower, provider: "facebook") %>
			<% if social_identity[0] != nil %>
				<% graph = Koala::Facebook::API.new(Koala::Facebook::OAuth.new("878916972138133","1c19d3ff9cf496854d4e506030f592b1").get_app_access_token) %>
				<% profile_path = graph.get_picture(social_identity[0].uid, type: "small") %>
				<%= image_tag profile_path, class: "person" %>
				<% else %>
				<%= image_tag "person.jpg", class: "person" %>
			<% end %>

      		<% user = User.where(id: follower) %>
      		<%= link_to user[0].firstname,profiles_index_path(follower), class: "follower-thumbnail" %>
      	<!--

			<%# if user_signed_in? %>

      		<div class="f-button">
			<a class="octicon octicon-plus"></a> 
			</div> 
      		
      		<%# end %>
      	-->

      	
      		</div>			



     
    
    <% end %>
  <% count += 1 %>
  <% end %>
  </div>



<div class="col-4 col-sm-4 col-lg-4">
		    <% count = 1 %>
	  		<% @followers.each do |follower| %>
			<% if count%3==1 %>

	<div class ="thumbnail">
      		<% social_identity = Identity.where(user_id: follower, provider: "facebook") %>
			<% if social_identity[0] != nil %>
				<% graph = Koala::Facebook::API.new(Koala::Facebook::OAuth.new("878916972138133","1c19d3ff9cf496854d4e506030f592b1").get_app_access_token) %>
				<% profile_path = graph.get_picture(social_identity[0].uid, type: "small") %>
				<%= image_tag profile_path, class: "person" %>
				<% else %>
				<%= image_tag "person.jpg", class: "person" %>
			<% end %>

      		<% user = User.where(id: follower) %>
      		<%= link_to user[0].firstname,profiles_index_path(follower), class: "follower-thumbnail" %>
    		
		  <!--

			<%# if user_signed_in? %>

      		<div class="f-button">
			<a class="octicon octicon-plus"></a> 
			</div> 
      		
      		<%# end %>
      	-->


      	</div>			



     
    
    <% end %>
  <% count += 1 %>
  <% end %>
  </div>



<div class="col-4 col-sm-4 col-lg-4">
		    <% count = 1 %>
	  		<% @followers.each do |follower| %>
			<% if count%3==2 %>
		
    				 	<div class ="thumbnail">
      		<% social_identity = Identity.where(user_id: follower, provider: "facebook") %>
			<% if social_identity[0] != nil %>
				<% graph = Koala::Facebook::API.new(Koala::Facebook::OAuth.new("878916972138133","1c19d3ff9cf496854d4e506030f592b1").get_app_access_token) %>
				<% profile_path = graph.get_picture(social_identity[0].uid, type: "small") %>
				<%= image_tag profile_path, class: "person" %>
				<% else %>
				<%= image_tag "person.jpg", class: "person" %>
			<% end %>

      		<% user = User.where(id: follower) %>
      		<%= link_to user[0].firstname,profiles_index_path(follower), class: "follower-thumbnail" %>
         <!--

			<%# if user_signed_in? %>

      		<div class="f-button">
			<a class="octicon octicon-plus"></a> 
			</div> 
      		
      		<%# end %>
      	-->
	
      
      	</div>			



     
    
    <% end %>
  <% count += 1 %>
  <% end %>
  </div>


</div>
<% else %>
<div class="follower-container"> 
	<div class="calvin-lonely-image">
	<%= image_tag "Hobbes-calvin-alone.png", height: "100%", width: "100%" %>
	</div>
	<div class="no-follower">
		No one is following <%= @userFirstName[0] %>.
	</div>
</div>
<% end %>

<style>
.working-stories{
  margin-top: -2.5vw;
  position: absolute;
  margin-left: 9vw;
}
.created-stories{
  margin-top: 8vw;
}
</style>

app/views/profiles/_followings.html.erb
<%= render "top" %>
<% if @numberOfFollowings>0 %>


<div class="followings-container">
<% if @numberOfFollowings >2 %>
<h4>Followings</h4>
<% else %>
<h4>Following</h4>
<% end %>
</div>	





<div class="followings-container">	
<div class="col-4 col-sm-4 col-lg-4">
     		<% count = 1 %>
	  		<% @followings.each do |following| %>
			<% if count%3==0 %>



      		<div class ="thumbnail">
      		<% social_identity = Identity.where(user_id: following, provider: "facebook") %>
			<% if social_identity[0] != nil %>
				<% graph = Koala::Facebook::API.new(Koala::Facebook::OAuth.new("878916972138133","1c19d3ff9cf496854d4e506030f592b1").get_app_access_token) %>
				<% profile_path = graph.get_picture(social_identity[0].uid, type: "small") %>
				<%= image_tag profile_path, class: "person" %>
				<% else %>
				<%= image_tag "person.jpg", class: "person" %>
			<% end %>

      		<% user = User.where(id: following) %>
      		<%= link_to user[0].firstname,profiles_index_path(following), class: "following-thumbnail" %>
      		
      		</div>			



     
    
    <% end %>
  <% count += 1 %>
  <% end %>
  </div>



<div class="col-4 col-sm-4 col-lg-4">
		    <% count = 1 %>
	  		<% @followings.each do |following| %>
			<% if count%3==1 %>

	<div class ="thumbnail">
      		<% social_identity = Identity.where(user_id: following, provider: "facebook") %>
			<% if social_identity[0] != nil %>
				<% graph = Koala::Facebook::API.new(Koala::Facebook::OAuth.new("878916972138133","1c19d3ff9cf496854d4e506030f592b1").get_app_access_token) %>
				<% profile_path = graph.get_picture(social_identity[0].uid, type: "small") %>
				<%= image_tag profile_path, class: "person" %>
				<% else %>
				<%= image_tag "person.jpg", class: "person" %>
			<% end %>

      		<% user = User.where(id: following) %>
      		<%= link_to user[0].firstname,profiles_index_path(following), class: "following-thumbnail" %>
      		
      		</div>			

    

    <% end %>
  <% count += 1 %>
  <% end %>
    </div>


<div class="col-4 col-sm-4 col-lg-4">
		    <% count = 1 %>
	  		<% @followings.each do |following| %>
			<% if count%3==2 %>
		
    				 	<div class ="thumbnail">
      		<% social_identity = Identity.where(user_id: following, provider: "facebook") %>
			<% if social_identity[0] != nil %>
				<% graph = Koala::Facebook::API.new(Koala::Facebook::OAuth.new("878916972138133","1c19d3ff9cf496854d4e506030f592b1").get_app_access_token) %>
				<% profile_path = graph.get_picture(social_identity[0].uid, type: "small") %>
				<%= image_tag profile_path, class: "person" %>
				<% else %>
				<%= image_tag "person.jpg", class: "person" %>
			<% end %>

      		<% user = User.where(id: following) %>
      		<%= link_to user[0].firstname,profiles_index_path(following), class: "following-thumbnail" %>
      		
      		</div>			


    
    <% end %>
  <% count += 1 %>
  <% end %>
  </div>
</div>
<% else %>
<div class="followings-container">
<div class="calvin-lonely-image">
	<%= image_tag "Hobbes-calvin-alone.png", height: "100%", width: "100%" %>
	</div>
	<div class="no-follower">
		 <%= @userFirstName[0] %> isn't following anyone.
	</div>

</div>
<% end %>


<style>
.working-stories{
  margin-top: -2.5vw;
  position: absolute;
  margin-left: 9vw;
}
.created-stories{
  margin-top: 8vw;
}
</style>

app/views/profiles/index.html.erb
<%= render 'tales/navbar' %>
<% userName =  @userFirstName[0] %>
<% content_for :title do %><%=  userName %><% end %>

<div class="profile-left">

          <div class="user-photo"> 
          <% social_identity = Identity.where(user_id: params[:format], provider: "facebook") %>
          <% if social_identity[0] != nil %>
          <% graph = Koala::Facebook::API.new(Koala::Facebook::OAuth.new("878916972138133","1c19d3ff9cf496854d4e506030f592b1").get_app_access_token) %>
          <% profile_path = graph.get_picture(social_identity[0].uid, type: "large") %>
          <%= link_to((image_tag profile_path), profiles_index_path(params[:format]), class: "wendy") %>
          <script>
          $(document).ready(function(){
         /*   var old_width = $('.user-photo img').width();
           var old_height = $('.user-photo img').height(); 
           

           var viewport_width=   $(window).width();
           var viewport_height=  $(window).height();


           var new_width =  viewport_width * (old_width/1440);
           var new_height = viewport_height * (old_height/801);


           new_width = new_width+"px";
           new_height = new_height+"px";
           $('.user-photo img').attr('width',new_width);
           $('.user-photo img').attr('width',new_height); 

                $('.content-section-story').css('margin-top','8.5vh');
            */

          });
          </script>
          <% end %>

          </div> <!-- end of user-photo -->
          


          <div class="user-name"> 
          <%= link_to userName, profiles_index_path(params[:format])%>
          </div> <!-- end of user-name -->
  





  <div class="bio-box">  <!--Founder and CEO, Ryte Club. Doer of things and learner of dreams. Imagining the world to be more interesting each day, every minute.  -->
  <%= render "bio" %>  
  </div><!-- end of bio -->

  <%= render "follow_button" %>
  <%= render "follow_track" %>

   </div><!-- end of profile-left -->



  



<% if params[:filter]=="followers"%>
  <div class = "stories-by-user-detail">
    <%= render "followers" %>
  </div><!-- end of stories-by-user-detail -->

<% elsif params[:filter]=="followings"%>
  <div class = "stories-by-user-detail">
    <%= render "followings" %>
  </div><!-- end of stories-by-user-detail -->
<% elsif params[:filter]=="followings-story"%>
  <div class = "stories-by-user-detail">
    <%= render "stories" %>
  </div><!-- end of stories-by-user-detail -->
<% elsif params[:filter]=="published"%>
  
    <%= render "published" %>
  
<% else %>
    <%= render 'story_by' %>
<% end %>
<!--
-->
<!-- end of stories-by-user-detail -->
<script>
  $(document).ready(function(){

    $('.follow-user').mouseup(function(){
      var url = "<%= profiles_index_path(params[:format], filter: 'followings') %>"   
      $(location).attr('href',url);
    });
    

    $('.followed-by').mouseup(function(){
      var url = "<%= profiles_index_path(params[:format], filter: 'followers') %>" 
      $(location).attr('href',url);
    }); 


    $('.follow-stories').mouseup(function(){
      var url = "<%= profiles_index_path(params[:format], filter: 'followings-story') %>" 
      $(location).attr('href',url);
    });

    $('.create-new').mouseup(function(){
      var url = "<%= new_tale_path %>"   
      $(location).attr('href',url);
      console.log("clicked");
    });
    




  });
</script>




 <style>
      .profile-bio-info{
        cursor: pointer;
      }

      .profile-bio-new{
  padding: 25px 0px;
  margin-top: -5vw;
  width: 15vw;
  margin-left: -5vw;
  font-size: 1vw;
  position: absolute;      }

      .profile-edit-button{
        text-align: right;
        cursor: pointer;
        margin-left: 7vw;
        margin-top: 0vw;
        position: absolute;
      }
      .create-new{
               color: green;
                border: 2px solid black;
                padding: 2vw;
                margin-left: 76vw;
                cursor: pointer;
                position: fixed;
                margin-top: 30vh;
                box-shadow: 2px 2px 2px rgba(0,0,9,0.5);
                width: 13vw;
      }

      .octicon-plus {  font-size: 4.4vw;
                      color: black;
                     margin-left: 2.7vw;}

      .write-new{
       
       margin-top: 1vh;

      color: black;

      }
        .write-new{font-family: "Oxygen", serif;
  font-size: 1.5vw;
  line-height: 1.6;
  text-align: left;
  letter-spacing: 0.01em;}

.profile-left{
  position: fixed;
  margin-top: 10vh;

}      
.user-name{
  position: relative;

}
.user-photo{
    top: 0vw;
}

.wendy{
  font-size: 1vw;
}

      </style>

      </section>

<% if user_signed_in? and current_user.id.to_s==params[:format].to_s %>      
<div class="create-new">
    <span class="mega-octicon octicon-plus"> </span>
    <p class="write-new"> Start Writing </p>
</div>
<% end %>