config/routes.rb
  

  

Story::Application.routes.draw do

  

  resources :plotphotos

  resources :talephotos

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"} 
  get '/users', to: 'users#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
   resources :users , only: [:edit, :update]

   resource :user, only: [:edit] do
     collection do
       patch 'update_role'
     end
   end
   resources :tales

  root  'tales#index'# =>, filter: "Story"
  get 'tales/list', to: 'tales#tales_list'
  get "homepages/index"
  get "activities/index"
  get "journals/index"
  resources :contacts
  resources :bios
  resources :invitations
  resources :sharings
  resources :follows
  get "profiles/index"

  
  
  
  get "/pages/id", to: 'pages#show'
  resources :fruits
  
  resources :plots do
    member do
      post 'update'
    end
  end
  

  match 'featured_stories', :controller => 'tales', :action => 'featured_stories', :via => [:get]
  match 'trending_stories', :controller => 'tales', :action => 'trending_stories', :via => [:get]
  match 'tales/new',  :controller => 'tales', :action => 'new', :via => [:post]
  match 'tales/:id',  :controller => 'tales', :action => 'show', :via => [:get]
  match 'profiles/:id', :controller => 'profiles', :action => 'index', :via => [:get]
  match 'profilesOf', :controller => 'profiles', :action => 'follow', :via => [:get, :post,:delete]
  match 'profilesOfU', :controller => 'profiles', :action => 'unfollow', :via => [:get, :post,:delete]

  match 'talesOf', :controller =>  'tales', :action => 'follow', :via => [:get, :post,:delete]
  match 'talesOfU', :controller => 'tales', :action => 'unfollow', :via => [:get, :post,:delete]

  match 'likesOf', :controller => 'tales', :action => 'like', :via => [:get, :post,:delete]
  match 'likesOfU', :controller => 'tales', :action => 'unlike', :via => [:get, :post,:delete]

  
  match 'fruit',:controller => 'fruits', :action => 'ruin', :via => [:get, :post,:delete]

end

app/models/tale.rb
class Tale < ActiveRecord::Base
	include PublicActivity::Common
  has_one :talephoto, dependent: :destroy
  has_many :tale_genres
  has_many :genres,  through: :tale_genres
  has_many :sharing
  belongs_to :user
	has_many :plots, dependent: :destroy #foreign_key: :trackable_id
  accepts_nested_attributes_for :plots
  #  default_scope { order('updated_at DESC')}
    scope :mystory, ->(user){where('user_id = ?', user) if user.present? }
    scope :not_featured, ->{where(featured: [nil, false])}
	  scope :recent, ->{joins(:plots).where('plots.created_at > ?', 30.days.ago).uniq}
    scope :filter, ->(name){ joins(:genres).where('genres.name = ?', name) if name.present? } 
    scope :featured, ->{where(featured: true).reverse.take(2)}
    scope :contributors, ->(tale_id){
      joins(:plots).where('plots.tale_id =?', tale_id).pluck('plots.user_id').uniq.map{|m| User.where(id: m).first }
    }

    
    
  	acts_as_followable
  	acts_as_likeable

  
end

app/controllers/tales_controller.rb
class TalesController < ApplicationController
  before_action :set_tale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :update, :create, :destroy, :tales_list]
  before_action :find_genres, only: [:index, :new, :edit]
  after_action :set_trending_data, only: [:create, :follow, :unfollow, :like, :unlike]

  # GET /fruitss
  # GET /fruits.json
  def index
    #@current_tales = Tale.includes(:plots, :genres).not_featured.recent.filter(params[:filter])
    #@featured_tales = Tale.includes(:plots, :genres).filter(params[:filter]).featured
    
    #@current_tales = Tale.where(private_flag: 0).order('trending_factor').first(6)
    @current_tales = Tale.where(private_flag: 0, featured: true).first(6)
    
    if user_signed_in?
    

    @followings = Follow.where(follower_type: User, follower_id: current_user.id,followable_type: User).pluck(:followable_id)
    @recently_followed_tales = []
    for f in @followings
      @recently_followed_tales.push Tale.includes(:plots, :genres).not_featured.recent.where(user_id: f)
    end
    
    

    
    end

      #   if user_signed_in? 
      #      redirect_to activities_index_path
      #    end

  end

  # GET /fruits/1
  # GET /fruits/1.json
  def show

    @contributors =  Tale.contributors(@tale.id)
    @tale_id = @tale.id
    @authors =  Tale.where(id: @tale.id).pluck(:user_id) 
    @followCount = Tale.find(@tale.id).followers(User).count 
    @likeCount = Tale.find(@tale.id).likers(User).count 
    @authorName = User.where(id: @authors[0]).pluck(:firstname)
    @titles =  Tale.where(id: @tale.id).pluck(:title) 
    @talecover = Talephoto.where(tale_id: @tale.id)
    @subheadings = Tale.where(id: @tale.id).pluck(:subheading) 


    if @tale.private_flag==1
      if user_signed_in?
        if current_user.id!=@tale.user_id
          redirect_to '/'
        end
      else
        redirect_to '/'
      end
    end
  end


  def tales_list
    if current_user.admin?
      @lists = Tale.all
    else
     flash[:notice] = "Go to hell!!"
    end
  end
  # GET /fruits/new
  def new
    @tale = Tale.new
    plots = @tale.plots.build
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits
  # POST /fruits.json
  def create
    @tale = Tale.new(tale_params)

    respond_to do |format|
      if @tale.save        
          #    @tale.create_activity :create, owner: current_user  
          # prevention of identity theft
          @tale.user_id = current_user.id
          @tale.save 
          taleId = @tale.id.to_s  


          #create notification
          Rails.logger.info("heelo Nishat Raihana");
          followers = Follow.where( followable_type: User, followable_id: current_user.id).pluck(:follower_id)

     followers.each do|follower|
          n = Journal.new
          n.notification_type = "StoryCreate"
          n.notification_id = @tale.id
          n.notification_to = follower
          n.save
     end     
      






          format.html { redirect_to :controller => 'tales', :action => 'show', :id => @tale.id }
          format.json { render action: 'show', status: :created, location: @tale }  

      else
        format.html { render action: 'new' }
        format.json { render json: @tale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1
  # PATCH/PUT /fruits/1.json
  def update
    respond_to do |format|

      if @tale.update(tale_params)#
        # prevention of identity theft
          @tale.user_id = current_user.id
          @tale.save 
        format.html { redirect_to '/', notice: 'Tale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tale.errors, status: :unprocessable_entity }
      end





    end
  end

  # DELETE /fruits/1
  # DELETE /fruits/1.json
  def destroy
   
     
     #remove notification 
     #remove plots  


    if current_user.id==@tale.user_id
    notifications = Journal.where(notification_type: "StoryCreate", notification_id: @tale.id)
    notifications.each do|notification|
      notification.delete
    end  


    @tale.destroy






    respond_to do |format|
      #format.html { redirect_to tales_url }
      format.html { redirect_to profiles_index_path(current_user.id) }
      format.json { head :no_content }
    end
  end


  end


  def follow
     @tale = Tale.find(params[:followings_id])
     current_user.follow!(Tale.find(params[:followings_id]))
     set_trending_data
     
     if(params[:home].to_i==1.to_i)
        redirect_to '/'
     else
        redirect_to :controller => 'tales', :action => 'show', :id => @tale.id
     end   




  end

  def unfollow
    @tale = Tale.find(params[:followings_id])

     #redirect_to :controller => 'plots', :action => 'new', :tale_id => params[:followings_id]
     Rails.logger.info "hello"
     Rails.logger.info params[:home]
     Rails.logger.info "hello"
     if(params[:home].to_i==1.to_i)
        redirect_to '/'
     else
        redirect_to :controller => 'tales', :action => 'show', :id => @tale.id
     end   

        
  end

  def like
    @tale = Tale.find(params[:followings_id])
    current_user.like!(Tale.find(params[:followings_id]))
    redirect_to :controller => 'plots', :action => 'new', :tale_id => params[:followings_id]  


  end

  def unlike
    @tale = Tale.find(params[:followings_id])
    redirect_to :controller => 'plots', :action => 'new', :tale_id => params[:followings_id]
 
    end


  def featured_stories
  #  @current_tales = Tale.includes(:plots).not_featured.recent
    
    @featured_tales = Tale.featured

  end

  def trending_stories
    @current_tales = Tale.includes(:plots).not_featured.recent
    @trending_stories = Tale.order('trending_factor').first(5)
  end

 


  def set_trending_data
      numberOfLikes =  Tale.find(@tale.id).likers(User).count 
      numberOfFollow = Tale.find(@tale.id).followers(User).count 
      numberOfExtension = Plot.where(tale_id: @tale.id).count


      numberOfFollowRecent = Follow.where(followable_type: Tale)
      numberOfFollowRecent = numberOfFollowRecent.where('created_at > ?', 3.days.ago).count
      
      numberOfLikesRecent = Like.where(likeable_type: Tale)
      numberOfLikesRecent = numberOfLikesRecent.where('created_at > ?', 3.days.ago).count

      numberOfExtensionRecent = Plot.where(tale_id: @tale.id)
      numberOfExtensionRecent = numberOfExtensionRecent.where('created_at > ?', 3.days.ago).count


    
      totalTrendingFactor = numberOfLikesRecent+(numberOfFollowRecent*2)+(numberOfExtensionRecent*3)
    
      t = Tale.where(id: @tale.id)
      t[0].trending_factor = totalTrendingFactor
      t[0].save 
    
  end   
  
  

   private
    def find_genres
      @genres = Genre.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_tale
      @tale = Tale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tale_params
      params.require(:tale).permit(:title, :subheading,:user_id, :genre_ids, :featured, :trending_factor, :cover, :private_flag, 

        :plots_attributes => [:description, :user_id])
    end
end

app/helpers/tales_helper.rb
module TalesHelper
  
  def plots_contributor(tale_id)  
    contributors = Tale.contributors(tale_id)
    contributors.map {|m| link_to m, profiles_index_path(m.id), class: "tale-contributor"}.join(",  ").html_safe
  end


  def shared_emails(tale_id)  
    shared_users = Sharing.where(tale_id: tale_id).pluck(:email) 
  end



end

app/views/tales/_current_tale.html.erb
<% content_for :title do %>Ryte Club :: Peer-to-Peer Homework Network <% end %>




<script>
/* This code is only applicable for the homepage. */
var homepage = 1;

$(window).scroll(function() {
    if(homepage==1){
    if ($(".navbar").offset().top > 50) {
        $(".navbar-fixed-top").addClass("top-nav-collapse");
    } else {
        $(".navbar-fixed-top").removeClass("top-nav-collapse");
    }}
});



$(document).ready(function(){
        $("ul.content").snapscroll();
});

</script>





<!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                
                <%= link_to(image_tag("logo.png", height: "50px"), '/', class: "logo-image") %>
                <%= link_to "write", new_tale_path %>
    
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                   <li><%= link_to "home","/" %></li>
                     <% if user_signed_in? %>
                        <li><%= link_to " #{current_user.firstname.downcase}",profiles_index_path(current_user.id) %></li>
                        <li><%= link_to " exit", destroy_user_session_path, method: :delete %></li>
                     <% else %>
                        <li><%= link_to " login", new_user_session_path %> </li>
                     <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>












<ul class="content">
    <li>



 <header class="intro">
        <div class="intro-body">          

                 <div class="blurred-back">
            <h1 class="brand-heading">Ryte Club</h1>
            <p class="intro-text">Welcome to our peer-to-peer homework network</p> 
              </div>




        </div>
    </header>

</li>

<li>

    <%= render 'about' %>

</li>
<li>

    <%= render 'join' %>

</li>


</ul>

    













<style>

.intro {     
  background: url("https://dyy410q63q7mo.cloudfront.net/Blue.jpg") 30% 40% no-repeat;
  background-position: center center;
  background-size: cover;
  height: 100vh;
  overflow-x: hidden;
  overflow-y: hidden;

 }




body {
    width: 100%;
    height: 100%;
    color: #fff;
    background-color: #fff;
}






<!-- first divsection -->



/* spooky code!!
remove it and it will break the layout */


ul.content {
  width: 100%;
}

ul.content li {
  display: block;
  
}

/* Eric Meyer's Reset CSS v2.0 - http://cssreset.com */
/* this workd for forced scroll */
ul,li {border:0;font-size:100%;font:inherit;vertical-align:baseline;margin:0;padding:0}


</style>

app/views/tales/_footer.html.erb
        <div class="footer-of-home">
        <%#= link_to "Feedback",   contacts_path %> &nbsp;&nbsp;&nbsp;
        <%#= link_to "Contact",   page_path('contacts_footer') %>&nbsp;&nbsp;&nbsp;
        <%#= link_to "FAQ",   page_path('about') %>&nbsp;&nbsp;&nbsp;
        &copy;&nbsp;<%= "Ryte Club,  All Rights Reserved" %>
        </div>



        <style>

        .footer-of-home{
          background: rgba(0, 0, 0, 0);
  width: 100%;
  height: 4vh;
  position: absolute;
  /* margin-bottom: 0px; */
  margin-left: 11.5vw;
  margin-top: 90vh;
  color: white;
  font-size: 1vw;
  font-family: "Helvetica Neue",Helvetica,"Myriad Pro","Lucida Grande",sans-serif;	
        }


        

        </style>

app/views/tales/_homepage_feed.html.erb
<div class="story-section">
    <div class="container">
        <div class="col-xs-18 col-md-12 col-ls-12"> 


<% if @current_tales!= nil %>
<% @current_tales.each do |tale| %>
     <% line_counter  = 0 %>
     <% char_counter = 0 %>
     <% title_word_counter = 0 %>
     <% title_char_counter = 0 %>

    <div class="homepage-meta-container">  
      <div class="homepage-content-container"> 

        <% talephoto = Talephoto.where(tale_id: tale.id) %>
          <% if talephoto[0] != nil %>
            <%= image_tag talephoto[0].cover_url(:thumb), class: "homepage-story-image-div" %>
            <% else %>
            <%= image_tag "no_cover.jpg", class: "homepage-story-image-div" %>
          <% end %>


              <p class ="homepage-story-title-wrapper">
                       <% title_word_counter = title_word_counter+tale.title.split.size %>
                       <% title_words = tale.title.split(' ') %> 
                       <% title_words.each do|title_word| %>
                          <% title_char_counter = title_char_counter + title_word.length %>  
                          <% if title_char_counter>47 %>
                              <% break %>
                          <% else %>
                          <% title_char_counter = title_char_counter + title_word.length %><%# end %>
                        <% end %>  
                        <% end %>
        <% tale_title = truncate(tale.title, length: title_char_counter){""} %>
        <%= link_to(tale_title.html_safe,tale) %>
        </p>

<!--
  <div class="homepage-wrapped-paragraph">
        <%# tale.plots.order(:id).each do |plot| %>            
            <%#= simple_format truncate(plot.description, length: 160){link_to "Read More",tale, class: 'read-more'} %>
            <%# break %>
        <%# end %>    
  </div>
-->
 <div class="homepage-wrapped-paragraph">
    <p>  
    <% if tale.subheading!= nil %>  
    <%=  sanitize(tale.subheading).truncate(120).html_safe%>
    <% if tale.subheading.length>120%>
    <%= link_to "Read More",tale, class: 'read-more'%>
    <% end %>
    <% end %>
    </p>
    </div>




<div class="homepage-extend-follow-share">  
<script>
$(document).ready(function(){
  $('.dropdown-toggle').dropdown();
});

</script>
    <% url = url_for(:controller => 'plots', :action => 'new', :tale_id => tale.id)  %>
    <ul class="nav nav-pills ">
    <% if user_signed_in? %>
        
      <%  if current_user.id == tale.user_id or shared_emails(tale.id).include?current_user.email %>
        <li role="presentation" style = "backgroud-color: white">              
              <%= link_to "  Contribute",url %> 
      <% end %>

   <% if tale.user_id !=  current_user.id %> 
        <% ifFollow =  current_user.follows?(Tale.find(tale.id)) %>
        <% if ifFollow %>
    <!-- never change the following lines' indentation, it requires for proper jquery navigation -->
    <li role="presentation"  style = "backgroud-color: white"><a href="javascript:void(0);"><div class = "homepage-story-follow" id="<%= tale.id %>">Unfollow</div></a></li>
        <% else %>
    <!-- never change the following lines' indentation, it requires for proper jquery navigation -->
    <li role="presentation"  style = "backgroud-color: white"><a href="javascript:void(0);"><div class = "homepage-story-follow" id="<%= tale.id %>">Follow</div></a></li>
        <% end %>
 <% end %>
 <% end %>
 
    
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
      Share <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <% url_for_twitter = "https:\/"+"\/"+"ryte.club\/"+"tales\/"+tale.id.to_s %>
      <% dataText = "Ryte Club story :: "  +tale.title + " \n \r " +url_for_twitter %>
      <% dataTextTwitter = "https://twitter.com\/"+"share?url=ryte.club&text="+ dataText  %>
      <% dataLink = "https://ryte.club\/"+ "tales\/"+tale.id.to_s %>
      <% dataLinkFull = "https://www.facebook.com\/"+"sharer\/"+"sharer.php?u="+dataLink %>
                  <li role="presentation"><%= link_to " Facebook",dataLinkFull, target: "_blank"%></li>
                            <li role="presentation"><%= link_to " Twitter",dataTextTwitter, target: "_blank" %></li>
    

      
    </ul>
  </li>
</ul>
</div>

       



   </div>  <!-- end of content-container -->
 </div> <!-- end of meta-container -->

<% end %>
<% end %>





<% if user_signed_in? %>
<script>
$(document).ready(function(){
  var command ;
  $(".homepage-story-follow").mouseup(function(e){
              var text_of_div = $(this).text();
              console.log(text_of_div);
              

              if(text_of_div == "Follow"){
                  console.log("follow detected");
                  $(this).html("UnFollow");
                  console.log("changed to unfollow");
                  command = 0;
                  autoSaveFollow(e.target, command,$(this).attr('id'));
                 
                
                }
              else{
                  console.log("unfollow detected");
                  $(this).html("Follow");
                  console.log("changed to follow");
                  command = 1;
                  autoSaveFollow(e.target, command,$(this).attr('id'));
                
              }

                
              });
});



function autoSaveFollow(context,command,tale_id){
  //console.log(tale_id);

  if(command==0){


                  var followData = {
                                    "follower_type": "User",
                                    "follower_id": "<%= current_user.id %>",
                                    "followable_type": "Tale",
                                    "followable_id": tale_id
                  };
                  

                  console.log(followData);
                  $.ajax({
                  type: "POST",
                  url: "/follows/",
                  contentType: "application/json; charset=utf-8",
                  dataType: "json",
                  data: JSON.stringify(followData),
                  success: function(data){}
                  }); 
                  
                  }
  if(command==1){
    
                $.ajax({
                type: "GET",
                url: "/follows/",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: "",
                success: function(data){   
                    for(var i=0; data[i];i++)
                      {
                        if(data[i].followable_type=="Tale" && data[i].followable_id==tale_id && data[i].follower_id=="<%= current_user.id %>"){
                          $.ajax({
                              type: "DELETE",
                              url: "/follows/"+data[i].id,
                              contentType: "application/json; charset=utf-8",
                              dataType: "json",
                              data: "",
                              success: function(data){}});
                          }
                      }
                  }
                });



  }  
}
</script>
<% end %>

                </div>
            </div>
        <footer>
        <div class="container-footer">
        
        <%= link_to "Feedback",   contacts_path, class: "ryte-club-footer" %> 
        <%= link_to "Contact",   page_path('contacts_footer'), class: "ryte-club-footer" %> 
        <%= link_to "FAQ",   page_path('about'), class: "ryte-club-footer" %> 
        

      </div>

</footer>

        </div>







<style> 

.container-about { 
  width: 100%;
  background: url("/assets/alexandria.jpg") 30% 40% no-repeat;
  background-size: cover;
   height: 600vh; 
  overflow-x: hidden;
  overflow-y: hidden;


}

.homepage-about-brand-heading { 
    position: relative;
    margin: 0vh 0vw 10vh 3vw;
    /* width: 36%; */
    color: #FFF;
    font-weight: 100;
    font-family: "calluna-sans",sans-serif;
    font-size: 7vw;
}

.homepage-about-moto{ 
position: relative;
width: 100%;
margin: 4vh 0vw;
color: #FFF;
font-family: Lucida,sans-serif;
font-weight: 200;
text-align: center;
font-size: 1.3vw;
}
















.feed-section {
    padding-top: 100px;
    height: 100vh;
    background-color: white;
    width: 100%;
    background-size: cover;
    overflow-x: hidden;
    overflow-y: hidden;


}

.content-section-story {
    height: 100vh;
    background-color: #fff;
}



@media(min-width:767px) {
    .content-section {
        padding-top: 150px;
    }

    

   
}







.container-footer {
position: relative;
display: inline-block;
width: 60%;
text-align: center;
padding: 0px;
margin-left: 20%;
}

footer {
padding: 20px 0;
background-color: black;
margin-top: 3vh;
padding-top: 5px;
border-top: 1px solid #eaeaea;
}

.ryte-club-footer  {
margin: 8px;
color: white;
font-family: Arial, sans-serif;
  font-weight: 200;

}

.ryte-club-footer:hover {

 background-color: transparent;
  text-decoration: none;
color: rgba(255,255,255,0.6)

}
.ryte-club-footer:active {

 color: rgba(255,255,255,1)

}
.ryte-club-footer:focus {
color: rgba(255,255,255,1)

}

.ryte-club-footer:visited {
color: rgba(255,255,255,1)

}

.nav>li>a:hover, .nav>li>a:focus {
text-decoration: none;
background-color: #ffffff;
}



</style>

 

app/views/tales/featured_stories.html.erb
<% content_for :title do %>Featured Stories<% end %>
<%= render "layouts/side_bar" %>

<div class="row">
      <%= render 'featured_tales' %>
    </div>
  
    <style>
 .thumbnail{
 	margin-top: 20px;
 	}
 	</style>   

app/views/tales/index.html.erb
    <%= render 'current_tale' %>

app/views/tales/new.html.erb
<%= render 'form' %>

app/views/tales/tales_list.html.erb
<%= render "layouts/side_bar" %>
<% if current_user.admin? %>
 <ul>
   <% @lists.each do |tale| %>
     <ul class="list-inline">
       <li><%= tale.title %> </li>
       <li><%= link_to "Edit", edit_tale_path(tale.id) %></li>
       <li><%= link_to '',tale, method: :delete, data: { confirm: 'Are you sure?' }, class: "octicon octicon-paintcan" %> </li>
     </ul>
    <% end %> 
  </ul>
<% else %>
  <p> <%= notice %></p>
<% end %>