config/routes.rb
  

  

Story::Application.routes.draw do

  

  resources :plotphotos

  resources :talephotos

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"} 
  get '/users', to: 'users#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
   resources :users , only: [:edit, :update]

   resource :user, only: [:edit] do
     collection do
       patch 'update_role'
     end
   end
   resources :tales

  root  'tales#index'# =>, filter: "Story"
  get 'tales/list', to: 'tales#tales_list'
  get "homepages/index"
  get "activities/index"
  get "journals/index"
  resources :contacts
  resources :bios
  resources :invitations
  resources :sharings
  resources :follows
  get "profiles/index"

  
  
  
  get "/pages/id", to: 'pages#show'
  resources :fruits
  
  resources :plots do
    member do
      post 'update'
    end
  end
  

  match 'featured_stories', :controller => 'tales', :action => 'featured_stories', :via => [:get]
  match 'trending_stories', :controller => 'tales', :action => 'trending_stories', :via => [:get]
  match 'tales/new',  :controller => 'tales', :action => 'new', :via => [:post]
  match 'tales/:id',  :controller => 'tales', :action => 'show', :via => [:get]
  match 'profiles/:id', :controller => 'profiles', :action => 'index', :via => [:get]
  match 'profilesOf', :controller => 'profiles', :action => 'follow', :via => [:get, :post,:delete]
  match 'profilesOfU', :controller => 'profiles', :action => 'unfollow', :via => [:get, :post,:delete]

  match 'talesOf', :controller =>  'tales', :action => 'follow', :via => [:get, :post,:delete]
  match 'talesOfU', :controller => 'tales', :action => 'unfollow', :via => [:get, :post,:delete]

  match 'likesOf', :controller => 'tales', :action => 'like', :via => [:get, :post,:delete]
  match 'likesOfU', :controller => 'tales', :action => 'unlike', :via => [:get, :post,:delete]

  
  match 'fruit',:controller => 'fruits', :action => 'ruin', :via => [:get, :post,:delete]

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
before_action :authenticate_user!
  def index
   @activities = PublicActivity::Activity.order("created_at desc")#.where(owner_id: current_user.friend_ids, owner_type: "User")
   @current_tales = Tale.includes(:plots).recent
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activities.html.erb
<div>


<%# user prompted to start a story and proceeded to new create a new story%>


<%#= link_to "Create a story",new_tale_path, class: "navbar-btn btn-info btn pull-left" %>

<% stories_by_me = Tale.where(user_id: current_user.id) %>
<% if stories_by_me.count == 0 %>
<%= "You didn't create any story" %>
<% else %>
<h2>Your Created Stories</h2>
<br/>
<div>
<% stories_by_me.each do |s| %>
    
    <% url = url_for(:controller => 'plots', :action => 'new', :tale_id => s.id)  %>

    <%= link_to s.title,url %>
    &nbsp;&nbsp;&nbsp;
    <%= link_to '',s, method: :delete, data: { confirm: 'Are you sure?' }, class: "octicon octicon-paintcan" %> <br />

    <% end %>
</div>

<% end %>



<div>
Follower update

<br />


<% @activities.each do |activity| %>
  <div class="activity">
    <% followers = Follow.where(follower_id: current_user.id, followable_type: User).pluck(:followable_id) %>

    <% if activity.owner_id!=nil %>
    <%#= activity.inspect %>
        <% if followers.include? activity.owner_id %>


        <% userFirstNames = User.where(id: activity.owner_id).pluck(:firstname) %>
        <%# userLastNames  = User.where(id: activity.owner_id).pluck(:lastname)  %>
        <%#userNames = userFirstNames[0]+ ' ' +userLastNames[0] %>

        <%#= link_to activity.owner_id.,  '/'	 %>
        <% if activity.trackable %>
        <%= link_to userFirstNames[0],  profiles_index_path(activity.owner_id)    %>
        <%= render_activity activity %>
        <% end %>
        <% end %>
    <%#  activity.owner_id created new story named %>
    <%# activity.trackable_id %>
    <br/>
    <% end %>
  </div>
<% end %>
</div>

app/views/activities/index.html.erb
<div class="create-story-container">
 <%= link_to "Create Story",new_tale_path, class: "button" %>
 
 
</div>




<div>
  <div class="row">
    <div class="span4" >
     <div class="col-md-4">         
        <%= render "created_stories" %>
    </div>
    </div>
    <div class="span4">
    <div class="col-md-4" >         

        <%= render "trending_stories" %>


      

    </div>
    </div>
    <div class="span4" >
     <div class="col-md-4">         
      

<%= render "featured_stories" %>  
    </div>
    </div>
    
</div>















<div class="row">
  <%= render 'tales/current_tale' %>
</div>



<style>
h2{
    text-align: left;
    font-family: "Crimson Text", Georgia, serif;
    font-weight: 400;
    font-size: 50px;


}
</style>